# Generated by Django 6.0.3 on 2026-03-23 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('attribute_type', models.CharField(choices=[('number', 'Числовой ввод'), ('select', 'Выбор из списка'), ('fixed', 'Фиксированная стоимость')], default='number', max_length=20, verbose_name='Тип')),
                ('rate', models.DecimalField(decimal_places=2, default=0, help_text="Для типа 'Числовой ввод': стоимость = ставка × введённое значение", max_digits=12, verbose_name='Ставка за единицу')),
                ('fixed_price', models.DecimalField(decimal_places=2, default=0, help_text="Для типа 'Фиксированная стоимость'", max_digits=12, verbose_name='Фиксированная стоимость')),
                ('unit', models.CharField(blank=True, help_text='Например: часов, респондентов, минут', max_length=50, verbose_name='Единица измерения')),
                ('is_cost_item', models.BooleanField(default=True, help_text='Если выключено — поле информационное, не влияет на стоимость', verbose_name='Участвует в расчёте')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('multiply_with', models.ForeignKey(blank=True, help_text='Стоимость этого атрибута будет умножена на значение указанного атрибута', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multiplied_by', to='calculator.attribute', verbose_name='Умножить на атрибут')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='calculator.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='calculator.section', verbose_name='Секция'),
        ),
        migrations.CreateModel(
            name='SelectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('rate', models.DecimalField(decimal_places=2, default=0, help_text='Стоимость / ставка при выборе данной опции', max_digits=12, verbose_name='Ставка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='calculator.attribute', verbose_name='Атрибут')),
            ],
            options={
                'verbose_name': 'Опция выбора',
                'verbose_name_plural': 'Опции выбора',
                'ordering': ['order'],
            },
        ),
    ]
