# Generated by Django 6.0.3 on 2026-03-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('default', 'Обычный (всегда виден)'), ('qualitative', 'Качественный'), ('quantitative', 'Количественный')], default='default', help_text='Влияет на видимость при переключении этапов в секции с переключателем', max_length=20, verbose_name='Тип модуля'),
        ),
        migrations.AddField(
            model_name='section',
            name='has_stage_toggle',
            field=models.BooleanField(default=False, help_text='Если включено — у секции появляется переключатель качественный/количественный/оба', verbose_name='Переключатель этапов'),
        ),
    ]
