# Generated by Django 6.0.3 on 2026-03-26 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_module_module_type_section_has_stage_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='cost_unit',
            field=models.CharField(choices=[('currency', 'Рубли (₽)'), ('hours', 'Часы')], default='currency', help_text='Часы — значение считается в часах (для расчёта ПШЕ). Рубли — прямые денежные расходы.', max_length=20, verbose_name='Единица стоимости'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='multiply_with',
            field=models.ForeignKey(blank=True, help_text='Результат этого атрибута будет умножен на значение указанного атрибута', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multiplied_by', to='calculator.attribute', verbose_name='Умножить на атрибут'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Для числового ввода: результат = ставка × значение. Для часов ставка=1.', max_digits=12, verbose_name='Ставка за единицу'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='unit',
            field=models.CharField(blank=True, help_text='Подпись поля ввода: часов, респондентов, минут', max_length=50, verbose_name='Единица измерения'),
        ),
    ]
