# Generated by Django 6.0.3 on 2026-03-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_attribute_cost_unit_alter_attribute_multiply_with_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_optional',
            field=models.BooleanField(default=False, help_text='Если включено — модуль отображается с чекбоксом, пользователь выбирает нужные', verbose_name='Опциональный'),
        ),
    ]
