# Generated by Django 6.0.3 on 2026-03-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_module_is_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='category',
            field=models.CharField(choices=[('method', 'Метод'), ('report', 'Отчётность'), ('work', 'Работы'), ('other', 'Прочее')], default='method', help_text='method — метод (шаг 2), report — отчёт (шаг 3), work/other — работы', max_length=20, verbose_name='Категория'),
        ),
    ]
