# Generated by Django 6.0.3 on 2026-03-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_add_module_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='hint',
            field=models.CharField(blank=True, help_text='Пояснение под полем ввода, видимое пользователю на фронтенде', max_length=255, verbose_name='Подсказка'),
        ),
    ]
