# Generated by Django 6.0.3 on 2026-03-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_add_attribute_hint'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodModule',
            fields=[
            ],
            options={
                'verbose_name': 'Метод / методология',
                'verbose_name_plural': 'Методы и методологии',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('calculator.module',),
        ),
        migrations.CreateModel(
            name='RecruitOption',
            fields=[
            ],
            options={
                'verbose_name': 'Ставка рекрута',
                'verbose_name_plural': 'Рекрут',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('calculator.selectoption',),
        ),
        migrations.CreateModel(
            name='ReportModule',
            fields=[
            ],
            options={
                'verbose_name': 'Тип отчёта',
                'verbose_name_plural': 'Отчётность',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('calculator.module',),
        ),
        migrations.CreateModel(
            name='WorkModule',
            fields=[
            ],
            options={
                'verbose_name': 'Блок работ',
                'verbose_name_plural': 'Работы и расходы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('calculator.module',),
        ),
    ]
