# Generated by Django 6.0.3 on 2026-03-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_methodmodule_recruitoption_reportmodule_workmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('stage', models.CharField(choices=[('qualitative', 'Качественный'), ('quantitative', 'Количественный')], max_length=20, verbose_name='Этап')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ставка (₽ за респондента)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Ставка рекрута',
                'verbose_name_plural': 'Рекрут',
                'ordering': ['stage', 'order'],
            },
        ),
        migrations.DeleteModel(
            name='RecruitOption',
        ),
    ]
